-- Kench al Rescate - Supabase setup
-- Run this in Supabase SQL Editor.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  nombre text not null,
  email text,
  dni text,
  telefono text,
  direccion text,
  role text not null default 'cliente' check (role in ('cliente', 'admin')),
  created_at timestamptz not null default now()
);

create table if not exists public.repairs (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  email text,
  nombre text not null,
  telefono text not null,
  dispositivo text not null,
  modelo text,
  descripcion text,
  estado text not null default 'pendiente' check (estado in ('pendiente', 'en_curso', 'completado')),
  created_at timestamptz not null default now(),
  updated_at timestamptz
);

create table if not exists public.sales (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  nombre text not null,
  telefono text not null,
  tipo text not null,
  modelo text,
  estado text,
  descripcion text,
  created_at timestamptz not null default now()
);

alter table public.sales add column if not exists estado_admin text not null default 'pendiente'
check (estado_admin in ('pendiente', 'aceptado', 'rechazado'));

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  nombre text not null,
  precio numeric(12,2) not null default 0,
  tipo text not null default 'Equipo',
  descripcion text,
  imagen_url text,
  estado text not null default 'disponible' check (estado in ('disponible', 'reservado', 'vendido')),
  created_at timestamptz not null default now(),
  updated_at timestamptz
);

create table if not exists public.purchases (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  product_id bigint references public.products(id) on delete set null,
  nombre text not null,
  email text,
  telefono text not null,
  estado text not null default 'pendiente_pago' check (estado in ('pendiente_pago', 'confirmado', 'cancelado')),
  created_at timestamptz not null default now(),
  updated_at timestamptz
);

alter table public.repairs add column if not exists email text;
alter table public.products add column if not exists imagen_url text;
alter table public.products add column if not exists especificaciones text;

alter table public.repairs drop constraint if exists repairs_email_formato;
alter table public.repairs add constraint repairs_email_formato
check (email is null or email = '' or email ~* '^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$');

update public.profiles
set nombre = 'Cliente'
where nombre is null
   or nombre !~ '^[A-Za-zÁÉÍÓÚÜÑáéíóúüñ'' -]{2,60}$';

alter table public.profiles drop constraint if exists profiles_nombre_formato;
alter table public.profiles add constraint profiles_nombre_formato
check (nombre ~ '^[A-Za-zÁÉÍÓÚÜÑáéíóúüñ'' -]{2,60}$');

alter table public.profiles drop constraint if exists profiles_dni_formato;
alter table public.profiles add constraint profiles_dni_formato
check (dni is null or dni = '' or dni ~ '^[A-Z0-9 -]{5,20}$');

alter table public.profiles drop constraint if exists profiles_telefono_formato;
alter table public.profiles add constraint profiles_telefono_formato
check (telefono is null or telefono = '' or telefono ~ '^\+[0-9]{10,15}$');

alter table public.repairs drop constraint if exists repairs_nombre_formato;
alter table public.repairs add constraint repairs_nombre_formato
check (nombre ~ '^[A-Za-zÁÉÍÓÚÜÑáéíóúüñ'' -]{2,60}$');

alter table public.repairs drop constraint if exists repairs_telefono_formato;
alter table public.repairs add constraint repairs_telefono_formato
check (telefono ~ '^\+[0-9]{10,15}$');

alter table public.sales drop constraint if exists sales_nombre_formato;
alter table public.sales add constraint sales_nombre_formato
check (nombre ~ '^[A-Za-zÁÉÍÓÚÜÑáéíóúüñ'' -]{2,60}$');

alter table public.sales drop constraint if exists sales_telefono_formato;
alter table public.sales add constraint sales_telefono_formato
check (telefono ~ '^\+[0-9]{10,15}$');

alter table public.profiles enable row level security;
alter table public.repairs enable row level security;
alter table public.sales enable row level security;
alter table public.products enable row level security;
alter table public.purchases enable row level security;

create or replace function public.is_admin(user_id uuid)
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = user_id and role = 'admin'
  );
$$;

grant execute on function public.is_admin(uuid) to authenticated;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, nombre, email, dni, telefono, direccion, role)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'nombre', 'Cliente'),
    new.email,
    new.raw_user_meta_data->>'dni',
    new.raw_user_meta_data->>'telefono',
    new.raw_user_meta_data->>'direccion',
    'cliente'
  )
  on conflict (id) do update
  set
    email = excluded.email,
    nombre = excluded.nombre,
    dni = excluded.dni,
    telefono = excluded.telefono,
    direccion = excluded.direccion;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

drop policy if exists "profiles_select_own_or_admin" on public.profiles;
create policy "profiles_select_own_or_admin"
on public.profiles for select
using (
  auth.uid() = id
  or public.is_admin(auth.uid())
);

drop policy if exists "profiles_insert_own" on public.profiles;
create policy "profiles_insert_own"
on public.profiles for insert
with check (auth.uid() = id and role = 'cliente');

drop policy if exists "profiles_update_own_or_admin" on public.profiles;
create policy "profiles_update_own_or_admin"
on public.profiles for update
using (
  auth.uid() = id
  or public.is_admin(auth.uid())
);

drop policy if exists "repairs_select_own_or_admin" on public.repairs;
create policy "repairs_select_own_or_admin"
on public.repairs for select
using (
  auth.uid() = user_id
  or public.is_admin(auth.uid())
);

drop policy if exists "repairs_insert_authenticated" on public.repairs;
create policy "repairs_insert_authenticated"
on public.repairs for insert
with check (auth.uid() = user_id);

drop policy if exists "repairs_update_admin" on public.repairs;
create policy "repairs_update_admin"
on public.repairs for update
using (
  public.is_admin(auth.uid())
);

drop policy if exists "sales_select_own_or_admin" on public.sales;
create policy "sales_select_own_or_admin"
on public.sales for select
using (
  auth.uid() = user_id
  or public.is_admin(auth.uid())
);

drop policy if exists "sales_insert_authenticated" on public.sales;
create policy "sales_insert_authenticated"
on public.sales for insert
with check (auth.uid() = user_id);

drop policy if exists "sales_update_admin" on public.sales;
create policy "sales_update_admin"
on public.sales for update
using (public.is_admin(auth.uid()));

drop policy if exists "products_select_all" on public.products;
create policy "products_select_all"
on public.products for select
using (true);

drop policy if exists "products_insert_admin" on public.products;
create policy "products_insert_admin"
on public.products for insert
with check (public.is_admin(auth.uid()));

drop policy if exists "products_update_admin" on public.products;
create policy "products_update_admin"
on public.products for update
using (public.is_admin(auth.uid()));

drop policy if exists "products_delete_admin" on public.products;
create policy "products_delete_admin"
on public.products for delete
using (public.is_admin(auth.uid()));

drop policy if exists "purchases_select_own_or_admin" on public.purchases;
create policy "purchases_select_own_or_admin"
on public.purchases for select
using (
  auth.uid() = user_id
  or public.is_admin(auth.uid())
);

drop policy if exists "purchases_insert_authenticated" on public.purchases;
create policy "purchases_insert_authenticated"
on public.purchases for insert
with check (auth.uid() = user_id);

drop policy if exists "purchases_update_admin" on public.purchases;
create policy "purchases_update_admin"
on public.purchases for update
using (public.is_admin(auth.uid()));

-- After creating your admin user from the website login/register flow,
-- run this once, replacing the email if needed:
--
-- update public.profiles
-- set role = 'admin'
-- where id = (
--   select id from auth.users
--   where lower(email) = lower('manzanabailarinafeliz@gmail.com')
-- );
--
-- If the admin profile is missing or incomplete, run this instead:
--
-- insert into public.profiles (id, nombre, email, dni, telefono, direccion, role)
-- select
--   id,
--   'Kench al Rescate',
--   email,
--   coalesce(raw_user_meta_data->>'dni', ''),
--   coalesce(raw_user_meta_data->>'telefono', ''),
--   coalesce(raw_user_meta_data->>'direccion', 'Villa Crespo'),
--   'admin'
-- from auth.users
-- where lower(email) = lower('manzanabailarinafeliz@gmail.com')
-- on conflict (id) do update
-- set
--   nombre = 'Kench al Rescate',
--   email = excluded.email,
--   role = 'admin';
